### ISSUE TITLE
How to make hook function in External Injector?

### ISSUE THREAD

**Issue by thienha1** [BryanGIG/KMrite#3]
I'm going to upgrade from External Injector with offset & hex byte but hook function seem easier than this because 
• More efficient
• Can return anything you want
• Can set up functions to call pointers in update.
Can you help me set up this like that?
Ex code:
`MSHookFunction((void *)getAbsoluteAddress("libil2cpp.so", 0x00000), (void *) GameMode_Update, (void **) &old_GameMode_Update);`

**Comment by RevealedSoulEven** [comment]
@thienha1 do you got something?

**Comment by BryanGIG** [comment]
This app is only for offset & hex bytes patches
