### ISSUE TITLE
game lib or memory ?

### ISSUE THREAD

**Issue by NettixCode** [BryanGIG/KMrite#3]
is this patch direct to game libil2cpp.so library or it patch the memory lib like gameguardian ?

**Comment by BryanGIG** [comment]
runtime patch into lib game.

**Comment by NettixCode** [comment]
i was tried it.. it was running perfectly .. is it can combine with lgl mod menu .. ?

https://github.com/LGLTeam/Android-Mod-Menu(c++)  or https://github.com/LGLTeam/Mod-Menu-With-Memory-hack(java)

im still learning so im not to many undestand how to combine it .. but ill try :)

**Comment by BryanGIG** [comment]
yes, it can be combined with lgl mod menu.
but don't use AIDE, because AIDE not support Kotlin at this moment
